name = "anime-scraper-engine"
main = "src/worker.ts"
compatibility_date = "2026-04-02"
workers_dev = true

[triggers]
crons = [
  "*/15 * * * *",
  "*/30 * * * *",
  "5 0 * * *",
  "20 */6 * * *",
]

[vars]
ANIMEFLV_BASE_URL = "https://www3.animeflv.net"
JIKAN_BASE_URL = "https://api.jikan.moe/v4"
GOOGLE_CSE_BASE_URL = "https://www.googleapis.com/customsearch/v1"
SCRAPER_MAX_CONCURRENCY = "6"
SCRAPER_REQUEST_TIMEOUT_MS = "15000"
SCRAPER_REQUEST_RETRY_ATTEMPTS = "1"
SCRAPER_LOG_LEVEL = "info"
R2_BUCKET = "anime-app"
R2_BUCKET_BINDING = "R2"
SCRAPER_CACHE_BINDING = "SCRAPER_CACHE"

[[r2_buckets]]
binding = "R2"
bucket_name = "anime-app"

[[kv_namespaces]]
binding = "SCRAPER_CACHE"
id = "ec0bd672948b491f8db50c1db333683b"
preview_id = "22a9caed414f4cb18df478bdd814768d"
