create table if not exists public.anime_jikan_details (
	anime_id text primary key references public.animes ("animeId") on delete cascade,
	mal_id bigint unique not null,
	mal_url text,
	matched_query text not null,
	matched_title text not null,
	match_score double precision not null,
	title text not null,
	title_english text,
	title_japanese text,
	synopsis text,
	background text,
	type text,
	status text,
	rating text,
	source text,
	season text,
	year integer,
	episodes integer,
	duration text,
	score double precision,
	scored_by integer,
	rank integer,
	popularity integer,
	members integer,
	favorites integer,
	titles jsonb not null default '[]'::jsonb,
	images jsonb,
	trailer jsonb,
	promos jsonb not null default '[]'::jsonb,
	genres jsonb not null default '[]'::jsonb,
	studios jsonb not null default '[]'::jsonb,
	external_links jsonb not null default '[]'::jsonb,
	streaming_links jsonb not null default '[]'::jsonb,
	relations jsonb not null default '[]'::jsonb,
	jikan_fetched_at timestamptz not null,
	jikan_expires_at timestamptz not null,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create index if not exists anime_jikan_details_jikan_expires_at_idx
	on public.anime_jikan_details (jikan_expires_at);
